// Data Reducers
export const SET_BACKGROUND_PICTURE = "SET_BACKGROUND_PICTURE";
export const SET_PROJECTS = "SET_PROJECTS";
export const SET_EDUCATION = "SET_EDUCATION";
export const SET_EXPERIENCE = "SET_EXPERIENCE";
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const SET_SKILLS = "SET_SKILLS";
export const SET_CONTACT = "SET_CONTACT";
export const SET_HANDLES = "SET_HANDLES";
export const POST_RESPONSE = "POST_RESPONSE";
export const LOADING_DATA = "LOADING_DATA";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const FORM_SUBMITTED = "FORM_SUBMITTED";
