export { default as AboutMe } from "./AboutMe";
export { default as Blog } from "./Blog";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as Navbar } from "./Navbar";
export { default as Projects } from "./Projects";
export { default as Resume } from "./Resume";
export { default as Services } from "./Services";
export { default as Testimonial } from "./Testimonial";
